### ISSUE TITLE
Pressing tab while paused toggles the scoreboard.

### ISSUE THREAD

**Issue by Kynan383** [ppy/osu-stable-issues#166]
The game takes into account pressing tab even when you're paused, which I think shouldn't happen.

**Comment by Kynan383** [comment]
Or at least not having the game consider an alt+tab as just pressing tab if you consider that tab being registered while paused is normal.

**Comment by smoogipoo** [comment]
Hmm Alt+Tab doesn't cause the game to detect a key press for me. Are you on Windows 10?

**Comment by Kynan383** [comment]
Yes I'm on Windows 10, every time I pause and tab out, when tab back in and press continue, the scoreboard will be showing as if I pressed tab while playing the map.

**Comment by Kynan383** [comment]
You can see it happen here if you want : https://youtu.be/rRfuoQz-6iw I pause at 1:47, tab out, and when I tab back in and unpause at 3:44 the scoreboard is showing even though I play with it hidden all the time.

**Comment by peppy** [comment]
I've pushed a zero-effort attempt to fix this even though we can't reproduce it. Please check cutting edge to see if it's resolved.

**Comment by Kynan383** [comment]
I tested just now and it still happens on first try on stable but not on cutting edge ! It seems you fixed it easily, thanks :D

**Comment by smoogipoo** [comment]
Closing as resolved.

**Comment by E223** [comment]
It seems like the current fix for this prevents the alt key from working as a scoreboard toggle key, but it can still be bound in settings (this was reported on the forums). Not sure if that was intended.  

Any chance this can be fixed in a way that does not cause that behavior?

**Comment by smoogipoo** [comment]
@E223 please make a separate issue.
