### ISSUE TITLE
Pausing while the music starts don't stop music and random problem with similar behavior

### ISSUE THREAD

**Issue by Ceotom** [ppy/osu-stable-issues#287]
If you press pause while the music starts the music will not stop and continue to play during the pause
*After that on this map (until game restart), in the standard mode, the circles become non-clickable (sliders and spinners can be held), taiko becomes completely unplayable.
*This not work on maps with cutscene.

This issue also may appear randomly after start playing a map, but in that case game restart is not required to fix this problem.

[Video with triggering this bug using pause](https://streamable.com/bptt7)
[Video with random issue appear](https://youtu.be/GwZ2fG8Lu6s)
[Original forum thread](https://osu.ppy.sh/community/forums/posts/7308546)

Game version: b20191227.1cuttingedge (On beta and stable is no such problem)

**Comment by WinterIsPretty** [comment]
I think I only had this issue when retrying before the map started and the song overlaying but that was a few months ago and it stopped after I quit

**Comment by Wieku** [comment]
I have the same problem on cuttingedge. But it's broken immediately after starting osu!. The only fix for one play is to restart the map by instant restart button ("~" is default I think). Restarting osu! or map by menu/song select doesn't fix this.

After some restarts by ~ it's broken completely now.

What's weird, when it's broken, I can drag the sliders by only dragging on graphics tablet or with mouse with LMB/RMB pressed (I have mouse buttons disabled).

**Comment by Ceotom** [comment]
Fixed in b20191229cuttingedge

**Comment by peppy** [comment]
I haven't changed anything yet. Are you sure this is solved?

**Comment by Ceotom** [comment]
No, i could not to reproduce in 10 minutes

**Comment by Wieku** [comment]
@Ceotom I still have this problem on b20191229cuttingedge. What i commented was on 20191229 actually.
How it looks like on my PC (osu! was right after start): https://streamable.com/4ryh3

**Comment by peppy** [comment]
@Wieku is that a result of the track not pausing? It's hard to really tell what's going on from your video so if you could explain it that would be helpful.

**Comment by Ceotom** [comment]
@Wieku, i thought the problem fixed because i couldn't reproduce it in 10 minutes.

**Comment by Wieku** [comment]
@peppy Sorry for not explaining. I think these issues are somewhat connected.
Explanation: It breaks off after map restart at 00:24, music was paused correctly then. From 00:34 to 01:05 I can drag sliders with a mouse button even when mouse buttons are disabled (00:33). At 01:24 you can see music playing in pause overlay. At 01:32 I clicked instant restart and map started to work correctly (But not always). At 01:44 music was paused correctly, clicked restart, map broke off again.
Sometimes maps don't work right after starting the game, sometimes I need to play one map or make one map restart.

**Comment by Ceotom** [comment]
This bug can be appear on replays also
[Auto replay (Bug on 1:00)](https://streamable.com/x6sxg)
[User replay (Bug on 1:03)](https://streamable.com/pu9p2)

**Comment by peppy** [comment]
No matter how hard I try I cannot reproduce this. That said, I've identified a potential cause and pushed a fix for it. Please update cutting edge and report back.

**Comment by Ceotom** [comment]
@peppy, problem still exists

**Comment by Ceotom** [comment]
@peppy seems this only happens if the skin have custom hitsounds.

**Comment by peppy** [comment]
From my end that seems quite hard to believe. Could you test a bit more and make 100% certain that's the cause?

**Comment by Ceotom** [comment]
@peppy yes, the hitsounds are blame, i checked some skins and saw that this does not happen with all skins.

Skins, which i was not able to reproduce:
Default
Abastina
Yugen Final
Skins, which i was able to reproduce:
#HKZ
REMILIA HD
My skin

[Link](https://mega.nz/#!ojRhBKDT!lmOOufZkTxBFNjMzcTyrYPUz3Ih6hRAQAxA1icW9D1c)

**Comment by peppy** [comment]
Thanks, will investigate further.

**Comment by Wieku** [comment]
I can confirm that on default skin everything works good.

Reproduced it on skins:
elohere
MasnoNi v1.1
idke+1.1
owoTuna 1.4

**Comment by Wieku** [comment]
Those skins: [Link](https://drive.google.com/open?id=1Gr1_GZrNv8CvaI6C-1pm7HnZFQbl1wa2)

**Comment by peppy** [comment]
Could you please reproduce with this osu!.exe (make a backup or your old executable first).

[osu!.exe.zip](https://github.com/ppy/osu-stable-issues/files/4009016/osu.exe.zip)

After reproducing, please attach runtime.log.

**Comment by Wieku** [comment]
[runtime.log](https://github.com/ppy/osu-stable-issues/files/4009036/runtime.log)

**Comment by Wieku** [comment]
Somewhere in the 1/3 of runtime I changed the skin to default but it's not mentioned in the logs

**Comment by peppy** [comment]
I may need a timestamp of when the issue started to arise.

**Comment by peppy** [comment]
Optimally, it would help if you make the issue arise, record the wall clock time, including seconds, then play in the broken state once then immediately quit, using alt-f4.

**Comment by peppy** [comment]
As an update, the provided log was enough, thanks. I've found the cause.

**Comment by peppy** [comment]
Please test against the latest cutting edge release.

**Comment by Ceotom** [comment]
Could reproduce. Fixed.

**Comment by peppy** [comment]
Thanks. Would appreciate at least one more confirmation

**Comment by Wieku** [comment]
It seems to be fixed for me.

**Comment by Stedoss** [comment]
Also seems to be fixed for me.

**Comment by peppy** [comment]
Great, safe to call this one closed!
