### ISSUE TITLE
Offset sounds earlier in editor after latest update

### ISSUE THREAD

**Issue by Peter-GHub** [ppy/osu-stable-issues#298]
So I have compared maps with older version and latest one with audio library update and it turned out offset is earlier in most of maps by about 10-20ms

**Comment by Peter-GHub** [comment]
I have asked around people even and they seem to have same problem, It's difficult to check snaps on maps and use correct timing

**Comment by peppy** [comment]
Please adjust your universal offset to compensate.

**Comment by peppy** [comment]
Also please describe your problem better. What does "offset is earlier in most maps" mean? Do you have to *change* the offset in the editor earlier by 10-20ms? Do you need to adjust your universal offset to -10~20ms?

**Comment by Peter-GHub** [comment]
If you change for example your offset in editor from earlier 305 to let's say 320 it will sound aligned in editor with instruments but earlier that 305 was perfectly aligned with instruments in older versions editor, gameplay doesn't seem to have that issue and audio is aligned with offset correctly so 305 would sound okay in gameplay but not in editor in new version when in older version both editor and gameplay was aligned well

**Comment by peppy** [comment]
Editor and gameplay are still aligned. If anything, the overall offset has changed. Not one or the other.

**Comment by Peter-GHub** [comment]
The best way to notice the difference will be actual example on map I will pick map that was affected by it noticeably https://osu.ppy.sh/beatmapsets/991368 on chorus of the song which is 00:48:546 objects seem to be too early you can notice it on lower speeds, after i switched my version to previous one it was once again aligned well. if you cant hear difference as it is 10-20ms try using 25%-50% speed it might distort waves but both still should in theory sound the same.

**Comment by Peter-GHub** [comment]
Also no the audio file and everything was the same

**Comment by peppy** [comment]
DO NOT change the playback speed. Only check at 100%.

If the issue is only at lower speed then SPECIFY THIS as it is a completely differently issue altogether. As the editor specificies, low speeds (<100%) should NOT be used for timing purposes.

**Comment by Peter-GHub** [comment]
I'm telling to lower speed as it's noticeable on them it's way more difficult to notice difference on 100% speed when it's 10ms-20ms you need good hearing for that

**Comment by Snowmander** [comment]
I think peppy is suggesting that universal offset changed after the latest update. I've noticed this too and had to change my UO. Have you calibrated UO on the latest version as well? 5+ms difference should be easily noticeable.

**Comment by Peter-GHub** [comment]
My Universal offset is set on 0 ms I think it's would be better to get more people to give opinion on this

**Comment by peppy** [comment]
I'm suggesting that nothing has changed at 100% playback. There *may* be a discrepancy below 100%, which I can potentially resolve.

We did extensive testing with this patch across hundreds of users and found an offset value which works for everyone. But we only test at 100%. Please test with your old offset while playing at 100%.

It's not that <100% makes it easier to hear issues. There are explicit code to *adjust* offsets below this rate because it becomes increasingly hard to calculate an accurate audio position as it gets slowed down, due to how the processing is applied.

**Comment by Darius-Wattimena** [comment]
Having the same issues, it's seems to happen with all playback rates and all beatmaps seems to have this issue.

**Comment by Peter-GHub** [comment]
I'm hearing difference at 100% it was just suggestion if you can't hear it

**Comment by Peter-GHub** [comment]
Some Beatmap Nominators noticed the problem on cutting edge so i have no idea how this got trough

**Comment by peppy** [comment]
Do not double post.

For anyone having issues, this is the *minimal information i require to actually take you seriously*:

- Did you test using the [official offset wizard](https://osu.ppy.sh/beatmapsets/4659#osu/24854)?
- Provide your runtime.log
- What is your audio hardware? If you're using a USB headset, can you try using your built-in sound card (analog output)?
- What is your operating system?
- What was your UO (Universal Offset) before this update?
- What do you need to set your UO to to get correct alignment in autoplay, after this update?

**Comment by Peter-GHub** [comment]
1. https://osu.ppy.sh/ss/14322572/7622
2. https://pastebin.com/HeszTD8e
3. Using standard headphones with minijack in motherboard ASUS-H110M-K
4. WIndows 10 64 Bit
5. 0 ms
6. I will see about that later it's hard to tell if it's only editor problem for now
7. Never enabled that

To prove it's not affecting only us:

- https://gyazo.com/96049018ab262b420620d51345dc38e1?token=2dfd33ebbf63e342bfa94cbe168e17b4 (Beatmap Nominators server)

- https://gyazo.com/60ba400ce23c65b25aadaf2d7bcfd138 (Beatmap Nominators server)

**Comment by Peter-GHub** [comment]
I will try to compare gameplay offset with editor one as well

**Comment by peppy** [comment]
Sunday is literally a week ago. There have been days since then. It's not relevant so please stop posting such nonsense.

I've pushed a potential fix to cutting edge. Please test there as soon as possible.

**Comment by Peter-GHub** [comment]
Huh why it's not relevant you rolled audio library week ago to cutting edge so the problem already existed, let me see potential change

**Comment by Peter-GHub** [comment]
Sorry for doublepost anyways:
- Week ago the change with audio library was rolled into cutting edge as you can see this particular version is mentioned
- Checked the latest cutting edge and it didn't seem to fix the problem

**Comment by nl-tatatat** [comment]
this is still an issue. Audio with compatibility mode off is 15ms later compared to osu! builds before the audio library change.

**Comment by peppy** [comment]
@nl-tatatat can you confirm that with playback at 100% there's no issue?

**Comment by nl-tatatat** [comment]
There is no issue at 100% playback.

**Comment by peppy** [comment]
This has been fixed on cutting edge, please test it as soon as you can!

**Comment by peppy** [comment]
Closing as fixed. Please comment if you still have issues.

**Comment by Peter-GHub** [comment]
From what I've seen this wasn't really fixed and it pissed off more and more people also https://github.com/ppy/osu-wiki/pull/3517 you said to open issue so i'd like to reopen it

**Comment by peppy** [comment]
Please open a new issue. This specific one was already resolved.
