### ISSUE TITLE
Circles increasingly off-beat

### ISSUE THREAD

**Issue by keysercam** [ppy/osu-stable-issues#306]
***Moved from osu! Help forums***
Player Name: Jazzieee
https://osu.ppy.sh/community/forums/topics/1006609

Problem details: Whenever I play a map (any map), the song starts out with the circles in sync with the song, but by the end of the map, the notes are very out of sync. It sounds like I need to change my offset, but in order to combat the problem, I would have to KEEP changing the offset as the song plays. This problem has started rather recently, within the last month or so, since I haven't played in roughly a month until now when I noticed the problem.

I recorded a video of what I'm talking about.
The map starts out fine. Around 2:28 you can see that the problem is getting a bit bad. It's at this point that I can't play a regular map. But since I was using the Relax mod, I was able to keep going.
3:53 is another good example of how out of time the circles have become.

Has anybody ever run into this issue before or know how to fix it? Please help! Thank you :)

Video or screenshot showing the problem: https://youtu.be/yyP5F87mke0

osu! version: Stable 20200104.8 (latest)

**Comment by keysercam** [comment]
I seem to have fixed the issue. 
It was a problem with conflicting, installed audio drivers.  In order to fix it, I disabled all audio drivers except for 1 (Which is Realtek Audio Drivers).  I am unsure why this didn't cause a problem in the past, however.

**Comment by keysercam** [comment]
It seems to be an issue with the new Bass DLL files.  Replacing them with Bass DLL files from 2016 fixed this issue entirely.

**Comment by peppy** [comment]
Please do NOT manually replace DLL files. It will result in more issues than you think. Please turn on audio compatibility mode if anything.

**Comment by keysercam** [comment]
I had thought that the issue was with conflicting audio drivers, so I tried disabling all but one audio driver.  I started testing a few maps, and they played fine, that was when I posted about it being fixed.  Unfortunately, I was wrong, and the few maps I played were only the beginning of the desync, so I didn't notice it until after I made the post.  I didn't want to cause more confusion, so I deleted the post.

I am also one who made the post about Audio Compatibility mode causing freezing and stuttering, so that unfortunately does not solve the issue either (issue https://github.com/ppy/osu-stable-issues/issues/318)

I have tried multiple headphones, earbuds, and a speaker system from different audio jacks on my PC, but the problem has persisted. 
For hardware ---

Processor: **Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz**
GPU: **NVIDIA GeForce GTX 1070**
Motherboard: **ASUS ROG STRIX Z370-E GAMING**
**16GB RAM**

**Comment by peppy** [comment]
Do you have a usb headset or something which is actually a different audio *output* device?

**Comment by keysercam** [comment]
![audio devices and drivers](https://user-images.githubusercontent.com/19848864/72036394-abe32880-3268-11ea-9ad5-8ee343696a12.PNG)

I attached an image my audio outputs and drivers.  The output that I use mainly is **Speakers (Realtek High Definition Audio)** and the only driver enabled is the Realtek High Definition Audio driver.  I have tried swapping my playback device to Realtek Digital Output already, but there was no change.

My headset plugs directly into the green line-out audio jack.  I have tried unplugging them, and using earbuds that plug into the same one but got no change. I also tried a speaker.  Then I plugged each of those into the front audio jack on my pc but still got no change for each of them.

If you need the actual name of the headset/speakers/earbuds I am using, please let me know.

**Comment by peppy** [comment]
Do you have a razer headset per chance (based on the listing it looks like you may). If so, could you give that a try via USB connecition?

**Comment by keysercam** [comment]
I do not have a Razer headset. This is my hardware:
Headset: **SENNHEISER PC360 3.5mm Connector Circumaural Headset**
Earbuds: **Sony MDRXB50AP Extra Bass Earbud Headset**
Speakers: **Razer Nommo 2.0 Gaming Speakers**

Unfortunately, none of them have a USB connection.

**Comment by peppy** [comment]
Do the razer speakers have a configuration app? Could you please open it and disable any enhancements of special features? Can you ensure windows [spatial audio](https://www.howtogeek.com/356481/how-windows-sonic-spatial-sound-works/) is off?

**Comment by peppy** [comment]
Also could you please test using the default skin?

**Comment by keysercam** [comment]
The Razer sound app that I have is the Razer Surround Sound app.  It is disabled.  Windows spatial audio is also disabled.

**Comment by keysercam** [comment]
The problem persists even when using the default skin.

**Comment by TehWolf105** [comment]
[https://dl.dropboxusercontent.com/s/7vmt48mq22fqido/Audio%20delayAD2_Trim_Trim.mp4](url)
![image](https://user-images.githubusercontent.com/59720303/72126806-87a44c00-333b-11ea-8cf4-7ac9be5d7135.png)

**Comment by peppy** [comment]
Could you please [try lazer](https://github.com/ppy/osu#running-osu) and see if the same thing happens? This may help us understand better where the issue is occurring.

**Comment by TehWolf105** [comment]
Yep, same thing. I'll add the video when it uploads.

**Comment by keysercam** [comment]
I am getting the same desync issue in osu!lazer.

**Comment by peppy** [comment]
We need to figure out why this is occurring.

Can both of you do the following:

- Start > Run > `mmsys.cpl`
- Double click your output device under the Playback tab
- Screenshot each tab of the dialog that appears

Hopefully there are some hints there

**Comment by TehWolf105** [comment]
Like this?
![rundll32_2020-01-11_13-41-59](https://user-images.githubusercontent.com/59720303/72209049-7ad94280-3478-11ea-8003-81ed31d21a63.png)
![rundll32_2020-01-11_13-42-09](https://user-images.githubusercontent.com/59720303/72209063-888ec800-3478-11ea-9e06-3194c4239f06.png)

**Comment by peppy** [comment]
Yes, but I'm also interested in the Levels / Enhancements / Advanced / Spatial Sound content.

**Comment by TehWolf105** [comment]
LCD is just my secondary monitor though I've tried playing without it with no change.

![rundll32_2020-01-11_13-46-04](https://user-images.githubusercontent.com/59720303/72209096-de637000-3478-11ea-8fd4-000556359d87.png)
![rundll32_2020-01-11_13-46-23](https://user-images.githubusercontent.com/59720303/72209100-e15e6080-3478-11ea-90aa-06c2f92e5d85.png)
![rundll32_2020-01-11_13-46-29](https://user-images.githubusercontent.com/59720303/72209106-e3c0ba80-3478-11ea-9e6b-93927db63b76.png)
![rundll32_2020-01-11_13-46-42](https://user-images.githubusercontent.com/59720303/72209109-e6231480-3478-11ea-87c4-45aba6006220.png)

**Comment by peppy** [comment]
can you try changing the "default format" to 44100 / 16bit and see if anything changes?

**Comment by TehWolf105** [comment]
No change at all.

**Comment by TehWolf105** [comment]
Update made it less frequent for me but still happens.

**Comment by keysercam** [comment]
![output 1](https://user-images.githubusercontent.com/19848864/72212161-0e286d00-34a5-11ea-932f-4b8c22ea303f.PNG)
![output 2](https://user-images.githubusercontent.com/19848864/72212162-108ac700-34a5-11ea-8353-f1c86adbac63.PNG)
![output 3](https://user-images.githubusercontent.com/19848864/72212164-11bbf400-34a5-11ea-8a25-31c08f41f25b.PNG)
![output 4](https://user-images.githubusercontent.com/19848864/72212166-12ed2100-34a5-11ea-8d0b-98bcdcf3b951.PNG)
![output 5](https://user-images.githubusercontent.com/19848864/72212169-14b6e480-34a5-11ea-9547-07844e41e3cf.PNG)

**Comment by keysercam** [comment]
Changing default format to 16 bit / 44100 hz had no change for me.

**Comment by keysercam** [comment]
I also found out that for me, if I pause the game, the circles and song re-sync (before desyncing like normal once again).

**Comment by peppy** [comment]
Does that work in both lazer and stable?

**Comment by keysercam** [comment]
Yes it does.

**Comment by plbriggs** [comment]
hello, ive been pointed in the direction of this forum as i have the same issues as described by you guys, but i also noticed that there is no solution as of yet, or at least for me. i started having this problem almost 3 months ago. Death from osu gave me some advicetelling me that if i removed the osu database file it could be fixed but it was only temporary. is this chat still active?

**Comment by peppy** [comment]
Can you confirm that deleting your database *does* help first of all? Does it fix it every time? If so, it sounds like an issue with the per-beatmap offset.

**Comment by plbriggs** [comment]
it did help at first like a month ago when i first tried it, but recently its only helped for about 15 minutes or so

**Comment by plbriggs** [comment]
regardless i might need to completely reset my pc because of other unrelated issues

**Comment by keysercam** [comment]
Deleting the osu database file did not help the issue at all for me.  I have yet to find an actual solution to this issue.  As stated above, replacing the bass dll files with earlier versions fixed the issue entirely, but peppy has strongly advised against it.  If you end up resetting your PC, please follow up with whether or not that actually fixed the issue.

**Comment by johngao2** [comment]
I had the exact same issue of the audio gradually going out of sync. What solved it for me was replacing the Realtek High Definition Audio driver with "High Definition Audio Device". To do this, go into device manager, and under "Sound, video and game controllers" right click "Realtek High Definition Audio" and select "update driver". Then, select "browse my computer for driver software" > "let me pick from a list of available drivers on my computer". From the list, pick "High Definition Audio Device" and restart your computer.

Your issue might have a different cause than mine, but I saw that you had the Realtek driver so this might be worth a try.

**Comment by peppy** [comment]
@johngao2 thanks for the information. if possible, could you list your hardware model and the driver which was causing issues (full version number)? may be helpful to implementing a fix for this issue from our end.

**Comment by johngao2** [comment]
Sorry, but what do you mean by hardware model? I'd love to provide info but I'm not sure what this refers to.

The driver was Realtek High Definition Audio and the version number was 6.0.1.8186.

**Comment by peppy** [comment]
If it's onboard audio, the motherboard model would be fine.

**Comment by johngao2** [comment]
The motherboard is ASUS PRIME Z-370 A.

**Comment by supercontact** [comment]
Hi, just want to mention that I'm also having this exact same issue. The problem suddenly appears today and it is fine when I last played a couple of weeks ago. Songs gradually going offbeat globally both in Osu! and Osu!Lazer. Restart the game re-syncs the song but it only last about 3 minutes when playing before going offbeat again.

I'm using headphone connected to my laptop and the driver is "Realtek high definition audio" version 6.0.1.8564. Laptop model is ASUS GL502VS.

**Comment by peppy** [comment]
Did you try changing drivers as above?

**Comment by supercontact** [comment]
I didn't change the drive. It seems the problem hasn't appeared today after I restart my PC. I will keep you posted if this happens again.

**Comment by Andyyy97** [comment]
Hey guys, i also have kind of the same issue. But it seems to appear randomly. When it happens, i can even quit out of the map and let auto play it or i can go in the editor and watch how the circles are behind the song. Starting a different Song solves the problem.
If I remember correctly the problem started when I got a VR headset. At that time I also got a new graphics card and upgraded from Windowns 8.1 to Win10. 
I tried different audio drivers like @johngao2 mentioned. 2 days ago I reinstalled Win10, but yesterday the problem appeared again. 

Processor: i7-6700K
GPU: RTX 2070 Super
Motherboard: Asus Z170 Pro Gaming
Headset: SteelSeries Arctis 3 

If you need any more information, please let me know.

**Comment by hugeturban** [comment]
I had the exact issue @keysercam had and resolved it today. I rolled back my BIOS firmware which fixed this.

Details:
I reinstalled Windows and also upgraded my BIOS firmware. After reinstalling osu I discovered this issue. The increasing hitsound offset was easily reproduceable and occured in every map.
Temporary solutions include:
1. Use 2016 bass.dll - causes audio "popping"
2. Use audio compatibility mode - increased hitsound latency

I downgraded my BIOS to the firmware I had before and the issue was fixed. I played the same map for 20minutes without any issue. Audio compatibility was off.

Perhaps this is more of a hardware related issue rather than a game bug.

**Comment by keysercam** [comment]
Been a while so I thought I'd update.

Today, I did a fresh install of Windows on the same hardware I've been using. This fixed the issue entirely for me. In fact, I backed up the entire osu! folder beforehand and am using the same osu! files as before the wipe, so it's safe to say that the issue for me had to do with something other than osu! itself.

Not sure if this helps anything, as not everybody can just go around wiping their HDD and re-installing Windows, but I thought it was worth mentioning.

Also, after the fresh install, the latency detector (I think that's what it is) in the bottom right corner of the game is showing latency roughly 1/50th of what it was before the reinstall (15ms --> 0.3ms, during gameplay)

**Comment by suntube** [comment]
any news on this issue? I still have it on osu standard and its only playable with audio compatibility option.. but the new engine is amazing.. :( please fix

**Comment by peppy** [comment]
@suntube do you get the same issue in lazer?

**Comment by suntube** [comment]
> @suntube do you get the same issue in lazer?

Yes, I do have the same issue on Lazer. It is preventing me from enjoying it as intended, I always wanted to shift to lazer and have fun there but everytime I try it out I face the same issue become unable to play.

Audio is one of the most essential elements in osu! game (and every rhythm game). The new engine is far superior than the older one, I'm hoping to see this issue get fixed so I can finally have fun with the new engine in both osu lazer and the current osu!

**Comment by ingenomus** [comment]
@peppy Unfortunately I have the same issue and I just found this thread. The offset also resets after I pause the map and continue but then it just increases more and more the longer the map goes on. I just tried playing on lazer and there it is much much worse. Also when I play shorter maps that don't have a skip section at the beginning, they start out fine. But when there is a skip section and I skip, the map already starts with a very noticeable delay that increases over time as well. I tried stable, cutting edge and beta but it's the same everywhere. I also reinstalled osu! on a different partition (my ssd) and moved my map folder over to the new installation but the issue kept persisting.

**Comment by suntube** [comment]
Is there any updates on this issue?
If anything is needed to provide I am here following this thread regularly.

**Comment by smoogipoo** [comment]
There haven't been any updates to this issue. I've made another issue for osu!lazer in the hopes that this can get more visibility, since neither I nor peppy can repro it.

**Comment by suntube** [comment]
Well, since I do have the issue persisting over the last year, I am willing to provide any needed data in order to determine the cause and hopefully fix it.

**Comment by peppy** [comment]
If anyone is still able to reproduce this issue, more video recordings (with URLs to the beatmap played) would be helpful in attempting to diagnose what is happening (since we still don't know).

**Comment by Attewir** [comment]
I am investigating and desperately trying to reproduce it (Currently appears too infrequently and non-consistently)
Here's my 2 cents so far:
I Suspect it has something to do with either Notifications flashing, Steam streaming devices, steam in general, having my specific apps open, EQ Modifications, having 3.5mm green earbuds in front panel while 3.5mm purple in back, DP audio to screen or something....

Oh and I heard it crack ONCE in song select too, so there's that.
ps. Since decreasing HZ decreases the issue, I'm trying to increase HZ to make the issue more frequent

**Comment by keysercam** [comment]
In response to Attewir’s message, I’d like to post all the information I had on my end.
- Firstly, I no longer have this issue. After a fresh Windows installation on the same exact hardware, the issue disappeared entirely.
- Before I did a fresh Windows install, the issue was never inconsistent. It was every day, every mapset, and every launch. No matter when I tried to play, no matter what map I tried to play (I tested hundreds), the out-of-sync issue still persisted
- I have never used a 3.5mm purple jack. I tried multiple audio devices in either 3.5mm green (front and back) without a difference.
- Replacing the bass.dll files with the old versions (2016) made the issue disappear completely (I was advised against this)
- The issue persisted in both osu! and osu!Lazer
- The rate at which the out-of-sync would occur on any map set depended on my current ms latency in osu! (The higher the ms latency, the faster they got off beat)
- Playing a mapset normally, with relax mod enabled, or autopilot enabled resulted in the increasingly offbeat issue. Allowing the mapset to play with Auto enabled showed no offbeat issue.

**Comment by Attewir** [comment]
Final post for me; I doubt it was a problem with osu! for me at least.
Updating windows, reinstalling audio drivers and uninstalling unnecessary Equalizer utility has resolved the issue for me.

**Comment by peppy** [comment]
Thanks for the update. Are you able to share what the equaliser utility was called?

**Comment by Attewir** [comment]
> Thanks for the update. Are you able to share what the equaliser utility was called?
This thing from Microsoft store:
https://www.microsoft.com/store/productId/9P2B8MCSVPLN

**Comment by Attewir** [comment]
Hey this reminds me, a quick fix attempt:
Try setting 100% Music, Sound and Master volume

**Comment by Phattyowo** [comment]
I'm pretty sure that I'm having this issue as well and I've not been able to come up with a good solution yet, even after trying almost all of the suggestions here. For me, resetting windows / updating windows and reinstalling audio drivers didn't seem to do much. Uninstalling realtek audio console however, helped out a bit, combined that with audio compatibility mode and the issue was much better. This wasn't a very good solution for me though, as audio combatibility mode has an issue where it makes the approach circles pretty laggy... Other than this, I've tried reinstalling windows to an older version, which I'm pretty sure is the last time my game was running fine. Since windows 11 just came out however, I don't really wanna go back. Please help!

**Comment by peppy** [comment]
Have you read the other posts and gone through every possible solution?

**Comment by Phattyowo** [comment]
Yes I'm very sure I have, I'm on a fresh install here so a few suggestions like extra services or devices causing delays is out of the question, except for that realtek audio console which I have uninstalled. I'd like to add that changing the sound settings to https://imgur.com/a/gcFr8fn also helped (only with audio compatibility mode on though). I've also tested out other rhythm games and it seems like muse dash and quaver seems to play fine. I'm happy to add any more information you'd need!

**Comment by peppy** [comment]
Unfortunately at this point there's nothing you can provide short of shipping us your PC in its current state. And even then, we'd probably be debugging an issue with a driver, external app, or in a best case scenario in the audio library we use.

I'm going to call out drivers. If you have an external sound card (ie. usb headphones will even work), please try this. If you don't have one, consider borrowing from a friend for testing.

**Comment by Phattyowo** [comment]
i have a pair of arctis 7s which has a usb wireless receiver, would this be a decent testing device? I've tested it and it still occurs, other than this I'll have to go get myself usb headphones to test as sound cards are a bit pricey over here. It does say the arctis 7 driver manufacturer is generic USB audio though!

**Comment by smoogipoo** [comment]
@Phattyowo Please provide your [dxdiag output](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).

**Comment by Phattyowo** [comment]
sure!
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/7326367/DxDiag.txt)

**Comment by peppy** [comment]
@Phattyowo and just for the record can you confirm it also happens on osu!(lazer) https://github.com/ppy/osu#running-osu ?

And tell us what you mean by "it gets better after uninstalling realtek control panel"? Becuse that sounds like a hint, but it's hard to understand unless you tell us how much it improves, and how far away it is from *fixing* the issue.

**Comment by Phattyowo** [comment]
i can confirm it happens on osu lazer. I'm not completely certain that my issue is exactly the same as @keysercam, but there definitely are some similarities. Uninstalling Realtek Audio Console doesn't do much by itself, but it is a combination of the three things I talked about that will make the issue less apparent (Uninstalling realtek audio console, enabling audio compatibility mode and changing up the sound settings).

**Comment by peppy** [comment]
What's the difference between "practically fixes" and "fixes"? And can you confirm that it still 100% occurs regardless of applications installed when compatibility mode is *disabled*?

**Comment by smoogipoo** [comment]
@Phattyowo Would also be interested in the following...

Can you install [LatencyMon](https://www.resplendence.com/latencymon) ([download link](https://www.resplendence.com/download/LatencyMon.exe)). It should look like the following:
![image](https://user-images.githubusercontent.com/1329837/136880959-ace8ca20-3ac4-4886-8d91-bc7924c91d83.png)

While in gameplay:
1. Press the "start monitor" button (top-left green button).
2. Play through a map, let it get out of sync.
3. Press the "stop monitor" button.
4. Take a screenshot of the "Main" and "Drivers" tabs.

**Comment by Phattyowo** [comment]
I can definitely confirm that it 100% occurs all the time when compatibility mode is disabled regardless if realtek audio console is installed or not. Please excuse my wording as what I meant was that audio compatibility mode doesn't seem to have fixed the issue entirely, I still see some delays at the end of a map, but it's definitely much more playable compared to when audio compatibility mode was off.

**Comment by Phattyowo** [comment]
here are the images you requested! @smoogipoo
![image](https://user-images.githubusercontent.com/88934594/136882954-a60e24b1-5acf-4bca-a445-1fd459775169.png)
![image](https://user-images.githubusercontent.com/88934594/136883064-1892f84e-4c0b-4b8c-9f1d-b598a56e2da4.png)
this is after running for 10 minutes: 
![image](https://user-images.githubusercontent.com/88934594/136884233-aafaa05c-2145-4ede-9672-8b7391019d45.png)
![image](https://user-images.githubusercontent.com/88934594/136884254-5a3eec00-933e-48c8-8606-5deb7f1bf934.png)
please note that I'm running on a fresh install of windows and have nothing running in the background (already closed off steam)

I'd like to add that I've now tested osu on 3 different devices and the same issue (or very similar) appears. one of the devices has 2ms frame time which appears to have made the desync even worse where I could no longer even hit a 300.

**Comment by peppy** [comment]
@Phattyowo three different devices with *different hardware configurations*??

This is an amazing revelation. It means that something you are carrying with you is likely causing the issue. Can you search for any common factors between all the systems? A list of anything you can think of will help. Are you plugging in a certain device? Are you using the same headphones? Do you have the same software running on these systems? Are they set to a weird language? Are you in a very hot environment?

**Comment by Phattyowo** [comment]
@peppy it sounds hard to believe, but this is all true and no matter what I do, I'm unable to play osu! properly. I have plugged in the same pair of headphones to all three of the systems, but that's about it. I tested using the device speakers and the same thing occurs. The only software I have running on all three systems is google chrome. The devices aren't set to a weird language and I'm not in a hot environment. There are 2 more things similar between these devices which is that they are running on the latest versions of windows and all using realtek drivers. I'm having a rather uncommon issue between all three devices so it's probably not osu!'s fault, but I've still not been able to fix it. On one of the devices, I've tested playing without audio and I'm still having issues, could there be something else wrong and not with the audio?

**Comment by Phattyowo** [comment]
Could this also be moved to another thread? I now feel like the issue may not be too similar to keysercam's

**Comment by peppy** [comment]
[latency_tester.zip](https://github.com/ppy/osu-stable-issues/files/7363805/latency_tester.zip) (https://github.com/peppy/test-windows-clock-sync if you wish to self-compile)

Could you please run this and return the log files it generates? It will take around 4 minutes. Also please close chrome before doing so.

Would be appreciated if you can also run on as many of the systems you have access to as possible.



> Could this also be moved to another thread? I now feel like the issue may not be too similar to keysercam's

It's the same issue, guaranteed. This thread is fine.

**Comment by Phattyowo** [comment]
Sure thing! I double clicked on the TestWindowsClockSync executable, but it doesn't seem to have done anything, I saw a command prompt pop up and disappear I think. Am I doing something wrong?

**Comment by peppy** [comment]
Try this one. I think I must have missed some dependencies:
https://drive.google.com/file/d/14GP9pt2jnzDavvE4LfUtXl1rJFHl5B_0/view?usp=sharing

**Comment by Phattyowo** [comment]
Here are the log files! I have one more device so I'll be sure to add the log files of that in a bit.

Main Device:
[run_20211018_103136_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7364124/run_20211018_103136_timeperiod.log)
[run_20211018_103136_baseline.log](https://github.com/ppy/osu-stable-issues/files/7364126/run_20211018_103136_baseline.log)

Device with the 2ms frame time:
[run_20211018_103025_baseline.log](https://github.com/ppy/osu-stable-issues/files/7364046/run_20211018_103025_baseline.log)
[run_20211018_103025_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7364048/run_20211018_103025_timeperiod.log)

Third Device:

**Comment by peppy** [comment]
Here's a newer version. I realised that the previous one was always testing using a virtual audio device. This one will run for 8 minutes (4 different logs)

https://drive.google.com/file/d/14KYXbHnfGmiiliS8BTVHZS6MP2RyW_H3/view?usp=sharing

**Comment by Phattyowo** [comment]
Here are the new log files! I've added in my third device's logs and confirmed that all devices still do have that weird issue.

Additional information (just speculation):
Upon my friend's return to osu! after about a month, he encountered delays as well (not entirely sure if his problem is similar to mine yet), but one of the things that he did during this time was updating to windows version 20h2. If a newer version of windows did somehow break the game on some devices however, I think this would make sense as originally keysercam said resetting windows fixed it for him (which would've probably reset his windows version to an older one).

Main Device (Personal PC):
[run_20211018_105944_real_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7364266/run_20211018_105944_real_timeperiod.log)
[run_20211018_105944_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7364267/run_20211018_105944_timeperiod.log)
[run_20211018_105944_baseline.log](https://github.com/ppy/osu-stable-issues/files/7364268/run_20211018_105944_baseline.log)
[run_20211018_105944_real_baseline.log](https://github.com/ppy/osu-stable-issues/files/7364269/run_20211018_105944_real_baseline.log)

Personal Laptop (w/ 2ms frame time):
[run_20211018_105758_real_baseline.log](https://github.com/ppy/osu-stable-issues/files/7364251/run_20211018_105758_real_baseline.log)
[run_20211018_105758_real_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7364252/run_20211018_105758_real_timeperiod.log)
[run_20211018_105758_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7364253/run_20211018_105758_timeperiod.log)
[run_20211018_105758_baseline.log](https://github.com/ppy/osu-stable-issues/files/7364254/run_20211018_105758_baseline.log)

Third Device (Borrowed Laptop):
[run_20211018_113609_real_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7364557/run_20211018_113609_real_timeperiod.log)
[run_20211018_113609_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7364558/run_20211018_113609_timeperiod.log)
[run_20211018_113609_baseline.log](https://github.com/ppy/osu-stable-issues/files/7364559/run_20211018_113609_baseline.log)
[run_20211018_113609_real_baseline.log](https://github.com/ppy/osu-stable-issues/files/7364560/run_20211018_113609_real_baseline.log)

**Comment by peppy** [comment]
Thanks. Unfortunately the logs don't show anything obvious yet. I'll design a few more tests, but in the mean time could you try running the test app while playing osu! (and confirming you get the drift in osu! during the test session)? Testing this on just one of the hardware configurations should be ample.

**Comment by Phattyowo** [comment]
Here are the results running the test app while playing osu on my main device! I have also confirmed that I still get the drift in osu! while running the test.
[run_20211019_062137_real_baseline.log](https://github.com/ppy/osu-stable-issues/files/7370781/run_20211019_062137_real_baseline.log)
[run_20211019_062137_real_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7370782/run_20211019_062137_real_timeperiod.log)
[run_20211019_062137_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7370783/run_20211019_062137_timeperiod.log)
[run_20211019_062137_baseline.log](https://github.com/ppy/osu-stable-issues/files/7370784/run_20211019_062137_baseline.log)

**Comment by peppy** [comment]
Thanks, these also don't show anything weird. I'll circle back with some more tests later today or tomorrow.

**Comment by JordyTearWater** [comment]
Just stumbled upon this thread and i have the exact same issue. When i start playing the game my offset appears to be fine, however after having played for a while my offset appears to be moving causing me to hit later and later. I have tried all earlier fixes in this thread and they don't seem to work.

I should add that i have had to manually resync my windows clock multiple times over the years when playing osu! i notice this because scores start showing that i posted them in the future.

I also ran the test you send and these are the results:
[run_20211019_192815_real_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7376223/run_20211019_192815_real_timeperiod.log)
[run_20211019_192815_timeperiod.log](https://github.com/ppy/osu-stable-issues/files/7376224/run_20211019_192815_timeperiod.log)
[run_20211019_192815_baseline.log](https://github.com/ppy/osu-stable-issues/files/7376225/run_20211019_192815_baseline.log)
[run_20211019_192815_real_baseline.log](https://github.com/ppy/osu-stable-issues/files/7376226/run_20211019_192815_real_baseline.log)

Considering you mentioned this might be a windows time issue i have gone ahead and tried the fixes described here: https://www.thewindowsclub.com/windows-10-clock-time-wrong-fix (Specifically i set clock synchronization to automatic and started the windows time service aswell as making the windows time service start automatically). 

I also found this site: https://time.is Which shows you if your local clock is synced correctly, i unfortunately didn't visit the site before applying the fixes so i can't compare results but it currently shows that my clock is at +0,007 seconds which is "perfectly synced". 

Im going to play the game again and see if the issue happens again or if these fixes helped. I hope this post might help in identifying and fixing this issue! 

EDIT: The issue has not repeated after 2 sepperate hour+ long sessions. Im still using audio compatibility mode right now but i will test without it aswell tommorow.

EDIT 2: Have played an hour without audio compatibility mode and the issue still hasn't returned. To add im using a FIIO K3 DAC with default windows drivers. 

EDIT 3: Having played more without audio compatibility i switched back because i started hitting late again (and switching to compatibility mode immediately fixed it).

**Comment by peppy** [comment]
@JordyTearWater so in your case it's very apparent that the issue does not always occur. Also that the logs you provided don't show anything weird. Maybe I need to make the test app run for longer so you can leave it running in the background over full play sessions and we can see if something is going on at a certain time point.

To make sure we are on the same page, can you describe exactly what you're seeing:
- Approximately how far out of sync does your game get?
- Once it's out of sync, does it stay that way even after restarting the beatmap or switching to another beatmap?
- Does it resolve when you change your audio device in osu! without restarting it?
- Does it temporarily resolve after restarting osu! in all cases? and get worse over time (if ever)?

**Comment by JordyTearWater** [comment]
Hello again, i didn't experience the issue for a little while but its back again. I managed to fix it again but first i will answer your questions.

**Approximately how far out of sync does your game get?**
* The unstable graph shows hitting 5ms late (so -5 +10) in error graph. Thats when i usually notice it and start trying to fix it.

**Once it's out of sync, does it stay that way even after restarting the beatmap or switching to another beatmap?**
* Yes, once this happens every single map i play will have me hitting 5ms too late

**Does it resolve when you change your audio device in osu! without restarting it?**
* Both of these don't change anything.

**Does it temporarily resolve after restarting osu! in all cases? and get worse over time (if ever)?** 
It doesn't appear to resolve after restarting osu (this time it literally started when i started osu) I don't know if it gets worse then +5 ms, this is when i start trying to change stuff.

So once i noticed that it was happening again i visited the site i linked earlier (https://time.is) and it showed that my clock was 3.4 seconds out of sync. The windows time service was still running but i decided to manually restart it and after refreshing the site it showed that my clock was perfectly synced again. 

https://imgur.com/a/Td8fiPW 

These two plays are 5 minutes apart, as you can see the unstable rate has gone back to normal after restarting the windows time service. Its weird but that appears to work for now.

**Comment by peppy** [comment]
only 5ms off? that’s actually below the precision of audio playback, so potentially out of scope.

this thread is dealing with larger differences, at least 10ms but usually far higher. can all other people in this thread please confirm they are seeing more than 10ms when experiencing this??

**Comment by Phattyowo** [comment]
i can confirm i see way more than 10ms. The game is pretty much unplayable for me, it goes up to 30ms (possibly more at times).

some accumulated info from fix attempts: 
- I'm almost certain the delay is higher the more i restart a map; restarting the game or quitting the map would reset this delay to what it was before
- It is less noticeable in a slower map
- It also seems like the hitsounds don't match up with the music
- I seem to get alot of misses and 100s in RX mode even though I'm aiming correctly (there seems to be a hitch or freeze before relax hits the circle?)
- My cursor seems to be a bit choppy
- Playing with HD and the same thing happens (approach circles are fine)
- Resetting my PC does nothing, I've tried this about 20 times by now
- Beatmaps work fine when put into quaver
- Delay is still definitely there in mania (and probably other osu! game modes) as well 
- Still no fixes on my end as of yet, for all I know my audio hardware seems to be working well and fine

**Comment by Attewir** [comment]
Iirc My avg. moved by 5-10ms, but never noticeably past 10ms.

**Comment by keysercam** [comment]
My issue was fixed last October, as I said in a post made back in October 11, 2020, but I thought I'd pitch it to confirm that when the issue was occurring I was definitely seeing more than 10ms.  (see video I uploaded along with making this thread for confirmation: https://youtu.be/yyP5F87mke0)

**Comment by peppy** [comment]
If there are any users which are getting well over 10ms, I'm willing to look into this again. Anything under 10ms is out of scope for this discussion (windows only offers ~5ms average precision which aligns with things occasionally being at a slightly different offset - we will work to improve on this in lazer with exclusive mode or ASIO or something else).

**Comment by Phattyowo** [comment]
yep I'm still getting the same issue, the delay or whatever is definitely well above 10ms. It happens very consistently and nothing has helped fix it so far, I've been gathering some information from my situation and have put them above in my previous message.

**Comment by mrink28** [comment]
experience all the same issues as in that issue, although for me its not constant between sessions, it sometimes happens and sometimes doesnt. Ive tried reinstalling audio drivers, trying in lazer, other stream releases but nothing fixes it. Every note i hit is always on the left of the unstable bar no matter the od so i know its not just me playing bad.

(sidenote- it starts to happen in between beatmaps not straight away)

Build- Latest 20211122.1

**Comment by mrink28** [comment]
Experiencing the same exact thing. I've tried reinstalling audio drivers, syncing windows clock, lazer, reinstalling osu and it hasn't fixed.

Could it potentially be a windows problem and have nothing to do with the game?

**Comment by mrink28** [comment]
For about 1 week everything went perfect, no breaks but yesterday night it just randomly started again continuing into today. I honestly have no explanation as of why it just stopped I'm really confused as the only action I've really done in the past week is clean up storage.

**Comment by peppy** [comment]
Are there any physical differences in your environment? Temperature fluctuations or otherwise? It may sound farfetched, but such things may be affecting real time clock.

**Comment by mrink28** [comment]
Actually you have a point, lately we have been using the air con more making my room a relatively cold environment. Is there anyway i can reset it?

**Comment by mrink28** [comment]
Im sure there already was another example in this thread but just for reference this is what my _break_ looks like 
![Screenshot (71)](https://user-images.githubusercontent.com/95530494/146507002-264b54da-c2b2-4851-b0b9-3766d14219d1.png). It suddenly shifts to the left.

**Comment by mrink28** [comment]
Hey peppy, I was just wondering if maybe the fact that im on windows 11 could be contributing to this problem.

**Comment by peppy** [comment]
> Hey peppy, I was just wondering if maybe the fact that im on windows 11 could be contributing to this problem.

no

**Comment by suntube** [comment]
Hi just wanted to update you guys on this issue as I used to have it and was following this post for long time.

It's been around 3 months since last time I had this issue, it immediately disappeared after I had what it seemed like "major" windows update, after that updated the issue was resolved. 

if you guys want more info I'm happy to assist

**Comment by mrink28** [comment]
Do you remember what update it was by any chance? Even so, my issue started within the last 3 months, hopefully whenever the next major update happens i experience the same outcome as you.

**Comment by suntube** [comment]
I'm very sorry I can't recall exactly what update was it, but I'm sure of one thing, it was a major update that made me feel like I formatted my PC, definitely felt different from any other update I've seen from windows. 

if there is a way to find out what update was it, then feel free to guide me so I can show you. 

I hope it gets solved for you as well.

**Comment by mrink28** [comment]
Hey peppy, just wanted to let you know that after realising a windows update helped fixed suntubes problem, I decided to take the risk and redownload windows from the recovery tab in settings. It's been an hour and the problem hasn't occurred. For all I can hope is that it doesn't start lol.

**Comment by mrink28** [comment]
Well this is great lol, my offset tends to break to the right now.

**Comment by Phattyowo** [comment]
It's been a while, but I'd like to add some information that'd be useful in solving my case. I recently noticed that my music and hitsounds seems to match up when playing with relax which is unlike keysercam's original post (https://youtu.be/yyP5F87mke0). While tapping with relax, my keyboard sounds and hitsounds seem to be in sync. I think it may be an issue / bug related to my inputs instead, is there any way to check up on this?

Here is a video showing that everything seems to be in sync with relax: https://www.youtube.com/watch?v=bSdhyw9IPnA&ab_channel=Phatty

**Comment by mrink28** [comment]
Well after nearly a month of this problem being really minimal its started to interfere again. I honestly have no idea what could be causing it it could just be something wrong with my laptop.

**Comment by peppy** [comment]
Is the temperature in your environment changing again? (just in case it comes across wrong, i'm not joking around at all and genuinely curious)

**Comment by mrink28** [comment]
Yes it was considerably colder in my room today, according to time.is my clock was ranging from 0.3-0.5seconds behind the actual time. On a side note on days when the room is natural temperature the problem never occurs but ive been noticing on specific maps it just randomly happens.

**Comment by smoogipoo** [comment]
Does this occur by using audio compatibility mode? Also please provide more info about your system such as CPU and motherboard name/model, headphones/output device name/model, and if you're using any external audio interface (DAC/AMP/etc).

Some of these can be found by posting a [dxdiag log](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe), but that may not contain the motherboard model which could be important in this case.

**Comment by mrink28** [comment]
Yes it also happens with audio compatibility. I play on a microsoft surface pro 6, the cpu is i5-8250u and gpu is intel uhd graphics 620. I have 8gb of ram. I use razer krakens and ant esports headsets. The problem occurs with both so i doubt its something to do with the headset as i only recently bought the krakens.

**Comment by Phattyowo** [comment]
My issue where the audio goes out of sync is most likely something related to the drivers as I was able to fix it temporarily a few times while trying out some audio fixes. I did try out syncing the time like others here, but it doesn't seem to work for me. Using window's high definition audio driver still had a delay and so did using the latest realtek drivers, I've tried alot of audio related fixes and none of them seem to fix the game permanently, I'm still working on a fix so I'll edit this post again if I'm able to find one.

edit: I still haven't fixed my problem yet

**Comment by mrink28** [comment]
Sorry for not providing an update but i downloaded a 3rd party time service instead of using windows time services. My issue has nearly completely gone now, it occurs sometimes but i manually sync my time and then it usually sorts itself out.

If the issue comes back I will follow your advice @Phattyowo . 

Thanks again for your help

**Comment by stbrouwers** [comment]
> Sorry for not providing an update but i downloaded a 3rd party time service instead of using windows time services. My issue has nearly completely gone now, it occurs sometimes but i manually sync my time and then it usually sorts itself out.
> 
> If the issue comes back I will follow your advice @Phattyowo .
> 
> Thanks again for your help

I have got the same issue happening to me too. Could you give me a more detailed explanation about your solution?
Thanks in advance.

**Comment by peppy** [comment]
@PS223934 the best we've figured from this is it can be environmental, and potentially related to your system clock shifting over time. you can try turning on windows automatic time sync, or running it manually from control panel when the issue occurs.

**Comment by wai-ho** [comment]
im starting to have this issue, the beginning is fine then the more i play, the more off beat it gets. ive been playing osu on the same laptop and same tablet and earphones for well over a year with no changes (same setup) and it circles randomly started to increasly off beat one day and been happening every time, i tried reinstalling osu but didnt work

**Comment by MyAzr** [comment]
literally same issue as wai-ho. Is there any solution to this?
https://www.youtube.com/watch?v=Cic9-lZAWvs

**Comment by stbrouwers** [comment]
@MyAzr it seems that for me, after switching from windows 10 to 11, this issue stopped occurring.
i am not necessarily suggesting you should switch too, but it might just be something driver related.
maybe a fresh install of windows will do the trick?

but as peppy stated before, this might also have something to do with your environment.
i switched from radiators to an airconditioner around the same time aswell, which overall proved to be way more stable in terms of keeping the same humidity and temperature.

**Comment by MyAzr** [comment]
> @MyAzr it seems that for me, after switching from windows 10 to 11, this issue stopped occurring. i am not necessarily suggesting you should switch too, but it might just be something driver related. maybe a fresh install of windows will do the trick?
> 
> but as peppy stated before, this might also have something to do with your environment. i switched from radiators to an airconditioner around the same time aswell, which overall proved to be way more stable in terms of keeping the same humidity and temperature.

wow I actually can't believe switching to w11 would help thx a lot. 
something still feels weird but maybe it's because of switching (or me being so paranoid by whole offset thing)

but kinda sad that to fix 1 game I need to switch, in any other rhythm game everything is fine.
and thanks again @PS223934
 
edit: well actually its still there but moving by 2-3 ms. but compare what was before it's more playable than not

**Comment by stbrouwers** [comment]
@MyAzr no problem :)

Soon i'll try to replicate this same issue on multiple devices to try and find what really causes it.
 
if you could give me some info about what your specs are, what kind of drive your game is installed on and what audio drivers, headphones/speakers and soundcard you're currently using, that would help a lot.

**Comment by MyAzr** [comment]
laptop predator helios 300 
Intel(R) Core(TM) i5-10300H CPU
GeForce RTX 2060
16 GB
1tb ssd

hyperx cloud 2 (kingston) | hyperx virtual surround sound driver
![image](https://user-images.githubusercontent.com/67195203/233299209-2a87d367-1815-48f9-b5fa-0482b6068f0a.png)
![image](https://user-images.githubusercontent.com/67195203/233299319-bafcf9b3-5360-46d2-adb9-d2f2cb262140.png)

**Comment by S4nr0kku** [comment]
I have the same issue but the difference is my sound driver is only the high definition audio device. I tried to update driver, restart my laptop and it didnt work for me. 1 week ago, my osu is normal when im playing but since yesterday theres something wrong with my audio and circle that starts to off beat. I also run the latencymon test that smoogipoo suggest and heres the result :

![Screenshot 2023-06-04 132436](https://github.com/ppy/osu-stable-issues/assets/135446327/ec51af2f-2cf2-4450-a181-3babc1b6f6e5)

I dont know if i had to downgrade or upgrade my windows 10 to 11 or fix the BIOS. I still dont understand why this happen to me. How to solve this problem?

**Comment by RobertoA1** [comment]
First of all, excuse my bad English. I have a very similar problem. Like everyone here, I have high latency when playing osu, like the music just doesn't go with the circles. I'm using a bluetooth headphones, it has a low latency mode, I have never had problems with it and the sound played while I clicked the circle. (but this "timing problem" happens with the speakers and wired headphones too) I installed osu!lazer, a week passed and suddenly the timing problem started. I checked the kernel latency time with LatencyMon and noticed that it had a very high value. (Always more than 12000). However, when I plugged in my bluetooth headphones and turned on the microphone, the problem was fixed, the kernel latency time returned to normal, and the game became playable again. Maybe that can help others. 

(before the microphone turned on, without any bluetooth headphones connected)
![image](https://github.com/ppy/osu-stable-issues/assets/46028277/31d4ddea-f5f7-44b9-93bb-1098b472c25d)

(after I connected my bluetooth headphones, without turn on microphone)
![image](https://github.com/ppy/osu-stable-issues/assets/46028277/f8cb5195-b31a-453a-9862-8515d5ecd971)

(after I connected my bluetooth headphones and turned on my microphone with any program, discord in this case)
![image](https://github.com/ppy/osu-stable-issues/assets/46028277/6f0251a4-8b41-4475-93fb-0562ec57e199)

When kernel timer latency goes to normal values, osu becomes playable and all goes well.
I haven't found another way to fix it without having to turn on the microphone.

Maybe the circles are off-beat because kernel timer latency's high values

EDIT: When I set my global offset to absurd random values (like 500ms or -500ms )(or +12ms [this is my kernel timer latency] , this works sometimes), I play and all seems worse, but later I return the offset to 0ms, and now off-set circles disappear and games becomes playable. But now, when I turn on the microphone, all seems fine, nothing happens, but if I turn off the microphone, osu has this "off-beat circles" again.

**Comment by peppy** [comment]
This is going to be something specific to your hardware. 

It's not related to this thread.

**Comment by peppy** [comment]
If you're still encountering this, please read https://github.com/ppy/osu/issues/31843 and test the provided fix if you're able!
