### ISSUE TITLE
osu!direct sometimes showing SR 0.0 even if it isn't 0

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu-stable-issues#383]
<img width="640" alt="screenshot768" src="https://user-images.githubusercontent.com/9590981/76538523-06d80c80-64b2-11ea-8ecd-e0c6b44d3ea5.png">

map on the screenshot: https://osu.ppy.sh/b/2275667

**Comment by peppy** [comment]
fixed.

**Comment by pavlukivan** [comment]
the problem still occurs on the latest cutting edge build
<img width="640" alt="screenshot775" src="https://user-images.githubusercontent.com/9590981/77223281-b2a5ea00-6b8d-11ea-8bb5-e4822c4c09ae.png">

Map in question: https://osu.ppy.sh/s/1118123

**Comment by pavlukivan** [comment]
(tagging @peppy just in case there's no notifications on closed issues or something)

**Comment by peppy** [comment]
it needs to be fixed on a per-beatmap basis.

**Comment by pavlukivan** [comment]
it happens a lot though

**Comment by peppy** [comment]
Please cite more examples.

**Comment by pavlukivan** [comment]
literally first search query that came to mind, 5 results in a row

<img width="640" alt="screenshot781" src="https://user-images.githubusercontent.com/9590981/77225189-91e69000-6b9f-11ea-91d9-659d7005f363.png">
<img width="640" alt="screenshot780" src="https://user-images.githubusercontent.com/9590981/77225190-93b05380-6b9f-11ea-9c87-4efb038ff3bb.png">
<img width="640" alt="screenshot779" src="https://user-images.githubusercontent.com/9590981/77225191-9448ea00-6b9f-11ea-85ac-89ecb8919467.png">
<img width="640" alt="screenshot778" src="https://user-images.githubusercontent.com/9590981/77225193-957a1700-6b9f-11ea-97b6-78c94432316f.png">
<img width="640" alt="screenshot777" src="https://user-images.githubusercontent.com/9590981/77225194-9612ad80-6b9f-11ea-8743-905d3a65ad46.png">

Maps:

- https://osu.ppy.sh/s/1128748
- https://osu.ppy.sh/s/1128160
- https://osu.ppy.sh/s/1126777
- https://osu.ppy.sh/s/1126206
- https://osu.ppy.sh/s/1125625

The maps listed here are all new, but the issue has been occuring for a long time. Maybe it needs time to update or something, it's still very annoying.

**Comment by pavlukivan** [comment]
Found another example from 3 months ago: https://osu.ppy.sh/b/2260609
<img width="640" alt="screenshot782" src="https://user-images.githubusercontent.com/9590981/77225306-7b8d0400-6ba0-11ea-9b3b-383ece5190ae.png">
