### ISSUE TITLE
All local scores wiped after playing

### ISSUE THREAD

**Issue by willyosu** [ppy/osu-stable-issues#60]
I had no issues with this in my first 5 years of playing osu!, but one day this summer after opening the game an error message popped up saying that my beatmap db was corrupt and all of my local scores and replays were wiped. This has continued to happen about every 2 weeks or so but I have no idea what triggers it (maybe corrupt beatmap or unexpected exit?). I have tried recovering the replays from the `osu!/Data/r` folder but there's only about 5% of the replays I had before actually in there, and using a backup of the scores.db also doesn't work at all; only loads those same scores.
![image](https://user-images.githubusercontent.com/11691902/65303839-1acb3300-db4d-11e9-8436-760813acbdb7.png)

**Comment by smoogipoo** [comment]
Can you post a few of those .bak files? Particularly interested in the first two in that list.

**Comment by willyosu** [comment]
Here's a zip with the first two, most recent, and a few other assorted ones.

[backups.zip](https://github.com/ppy/osu-stable-issues/files/3637919/backups.zip)

**Comment by smoogipoo** [comment]
Fixed on the next cutting edge build. You should be able to use any of those previous scores.db files (just remove everything after the `.db` in the filename).

**Comment by maia011** [comment]
Still getting the error message, build b20191006.1, Release stream: stable. I haven't made any substantial changes to my osu! folder and I haven't added any new beatmaps recently.
![Untitled](https://user-images.githubusercontent.com/56280235/66354574-a6a9d100-e93b-11e9-81ef-0646ad0f4753.png)

**Comment by peppy** [comment]
could you please post your backup db files as above?

**Comment by maia011** [comment]
Where do I find these? I couldn't find them in my osu! folder or in the Data folder, only the scores.db file. I do have osu.db.bak files though, so I'll upload those too. Sorry if I couldn't provide the files you needed 
https://files.catbox.moe/lqgjvv.zip

[scores.zip](https://github.com/ppy/osu-stable-issues/files/3700222/scores.zip)

**Comment by smoogipoo** [comment]
Those files are what we needed. Can you confirm that this is happened after at least two startups of b20191006.1? If this happened right after the update, it's likely that the previous version corrupted the database during its restart, and we can't do anything about that.

**Comment by maia011** [comment]
I can confirm that I've opened the game more than twice after the update. Thanks in advance :)

**Comment by smoogipoo** [comment]
Can you make a separate issue for this please? It's not relevant to the score database.
