### ISSUE TITLE
Updating beatmap but suddenly turns to be a new map 

### ISSUE THREAD

**Issue by Scathcier** [ppy/osu-stable-issues#637]
A while ago i was mapping my map in offline,
there is no username what so ever just plain guest in the username field
then i map that map for around 40min~ and then saved it

i tried to update the beatmap right away after saving it (in offline situation) and it tells me to log in.
I close the beatmap and log in to my acc and i tried to upload it, but the option is "sumbit  as a new map"
tried to refresh all the beatmap, restart osu, and even the computer, but its still says new map.
I keep upload it beacuse i think there was a bug, and still going to updating the existed map, but it creates new one instead

As the result, now i have 2 same exact beatmap (but every updates is only applied to the new one) .
Whenever I download the original or new one, it ask to update (in osu editor menu).
and when i pressed the update button, it updates to the original one

Edit**
I also have tried to change the beatmap id from the new one to original (and reverse), but it doesnt work.
its automatically synchronizing with the original one in the server (idk tho its just a guess)

link to new one
https://osu.ppy.sh/beatmapsets/1335767#osu/2767346

link to original
https://osu.ppy.sh/beatmapsets/1224505#osu/2708458

sry for the bad english thx

**Comment by peppy** [comment]
I've removed the new upload. Please download the original and apply your changes to it.

**Comment by Scathcier** [comment]
It doesnt work, ive replaced it with the original and still uploading as a new map
i also tried to clear the cache
![image](https://user-images.githubusercontent.com/77221133/104152654-c1a6a300-5412-11eb-884d-ea264e24cc7b.png)

**Comment by peppy** [comment]
Your client-side map is definitely not in a good state. Could you please zip and upload the folder from your Songs folder? And also make sure it doesn't exist in multiple folders within Songs?

**Comment by Scathcier** [comment]
[New folder (2).zip](https://github.com/ppy/osu-stable-issues/files/5794364/New.folder.2.zip)

**Comment by peppy** [comment]
The .osu file contains references to the new version I deleted. Please update the IDs to reference the old one

![image](https://user-images.githubusercontent.com/191335/104334546-d9c31300-5535-11eb-8814-cb89b68e1e40.png)

**Comment by Scathcier** [comment]
yes, i have tried it multiple times but everytime i did its just automatically revert back as soon as pressed the "update beatmap" button and then the new beamap is submitted as new

**Comment by peppy** [comment]
Please try again, since i already fixed this issue from our side in theory.

**Comment by Scathcier** [comment]
um, its still not fixed yet but its okay.
ill just create fresh one instead, can you delete the map tho ?
and its okay to close this issue btw thxx

**Comment by peppy** [comment]
How did you even submit if you were at your submission cap? I'm so confused.

**Comment by Scathcier** [comment]
actually i got 1 map graveyarded just yesterday so i still have slot, and the original one is gonna get graveyarded too in 2-3 days, so i can actually delete it manually
